discord.botToken: "changethis"
discord.channelID: "changethis"
discord.serverID: "changethis"
discord.useRoleColor: "true"
discord.stripMessageFormatting: "true"
discord.chatFormat: "**<NICKNAME>**: <MESSAGE>"
discord.joinFormat: "<NICKNAME> joined the game"
discord.leaveFormat: "<NICKNAME> left the game"
discord.postConnections: "true"
minecraft.stripMessageFormatting: "true"
minecraft.messageCharacterLimit: "500"
minecraft.postRawMessages: "true"
minecraft.messageFormat: "$91<COLOR><RANK>&r$93 <NICKNAME>$58 <MESSAGE>"